race/urls.py
from django.conf.urls import url
from . import views

app_name = 'race'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

rmsys/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^runner/', include('runner.urls')),
    url(r'^race/', include('race.urls')),
]

runner/urls.py
from django.conf.urls import url
from . import views

app_name = 'runner'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

race/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Race(models.Model):
    date = models.DateField()
    location = models.CharField(max_length=64, blank=True)
    distance = models.DecimalField(max_digits=5, decimal_places=2)
    event_name = models.CharField(max_length=64)

    def __str__(self):
        return self.event_name

runner/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date

# Create your models here.
class Runner(models.Model):
    curr_year = date.today().year
    GRAD_YEAR = [(i,i) for i in range(curr_year+1,curr_year+5)]

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    nickname = models.CharField(max_length=64, null=True, blank=True)
    gradyear = models.IntegerField(choices=GRAD_YEAR)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

race/views.py
from django.shortcuts import render
from .models import Race

# Create your views here.
def index(request):
    season = Race.objects.all()
    return render( request, 'race/index.html', {'season': season})

runner/views.py
'''
from django.shortcuts import render

# Create your views here.
def index(request):
    roster = Runner.objects.all()
    return render( request, 'runner/index.html', {'roster': roster})
'''


from django.views import generic
from .models import Runner

class IndexView(generic.ListView):
    template_name = 'runner/index.html'
    context_object_name = 'roster'

    def get_queryset(self):
        return Runner.objects.all()

class DetailView(generic.DetailView):
    model = Runner
    #template_name = 'runner/detail.html'

race/templates/race/index.html
{% if season %}
    <h1>Season:</h1>
    <ul>
    {% for race in season %}
        <li>{{race}}</li>
    {% endfor %}
    </ul>
{% else %}
{% endif %}

runner/templates/runner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}rscat{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          xmlns="http://www.w3.org/1999/html">
    <link href='https://fonts.googleapis.com/css?family=Rye' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'runner/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'runner:index' %}">rscat</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'runner:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Runners
                    </a>
                </li>
                <li>
                    <a href="{% url 'race:index' %}">
                        <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>&nbsp; Races
                    </a>
                </li>
                <li>
                    <a href="">
                        <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp; Review
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'runner:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

runner/templates/runner/index.html
{% extends 'runner/base.html' %}

{% block title %}Runner Roster{% endblock %}

{% block body %}
    {% if roster %}
        <h1>Roster:</h1>
        <div class="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Firstname</th>
                        <th>Lastname</th>
                        <th>Graduation</th>
                    </tr>
                </thead>
                <tbody>
                    {% for runner in roster %}
                        <tr>
                            <td>{{ runner.first_name }}</td>
                            <td>{{ runner.last_name }}</td>
                            <td>{{ runner.gradyear }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
    {% endif %}
{% endblock %}